/**
 * The recorded CLI surface, replayed against the port — from `node --test`, so it runs on both
 * CI platforms and survives `rituals/harness.py`.
 *
 * WHAT IS RECORDED AND WHY IT HAD TO BE. The CLI table was generated by walking argparse, and
 * `bin/geneseed-cli.mjs` parses its own argv out of the result — so the CLI's single source of
 * truth was a Python function in a file this migration deletes. `tests/record_help.py` freezes
 * the RENDERED help while the parser exists; this replays it. The table itself needed no
 * recording, because P2 moved it to `js/cli-table.json` and made it the owned document: a
 * second frozen copy of a file the tree already owns would be a claim nothing keeps true, and
 * one that could never be re-recorded once the parser is gone.
 *
 * `tests/harness_golden.py` HAS ZERO `--help` CELLS. This surface had never been compared once,
 * and the first comparison found the port answering `geneseed: error: unrecognized arguments:
 * --help` with exit 2 on all 26 verbs. `docs/declined.md` carries the adjudication; what is
 * asserted here is the outcome of it.
 *
 * THE ONE DELIBERATE DIVERGENCE IS AN ARGUMENT, NOT A FUDGE. The reference names itself
 * `harness`, after the file being deleted; the port names itself `geneseed`, as every error it
 * already prints does. `prog` is therefore a parameter of `formatHelp`, the fixtures are
 * replayed with the reference's own prog — so the layout is gated byte for byte — and the
 * shipped spelling is asserted separately, below.
 *
 * ⚠ THERE ARE NOW TWO POPULATIONS OF VERB, AND THIS FILE NAMES BOTH.
 *
 * The corpus can only ever hold verbs that HAD a CPython original: its recorder renders help
 * from the live argparse object and refuses outright when the parser and the table disagree
 * about which commands exist. `catalog`, `mcp` and `memory` never had a subparser — the
 * information behind them lived only behind web endpoints — so there is nothing to record for
 * them and nothing that could ever be recorded. Declaring them to argparse so the recorder
 * would emit a text is the move this project has rejected before under its own name: it would
 * be authoring the expected value in Python and then recording it back, which is a copy of a
 * value under test wearing a corpus's clothes.
 *
 * So they get an ABSOLUTE gate instead of a comparison. `RECORDED` is the corpus's own verb
 * list; `NATIVE` is the table minus it, asserted to be exactly the three by name, so a fourth
 * verb cannot arrive in either population unnoticed — the native list fails, loudly, rather
 * than the new verb slipping through ungated. What the native three are then held to is the
 * set of layout properties `layoutClaims` states, every one of which is CHECKED AGAINST ALL 26
 * RECORDED TEXTS in the same run: they are argparse's own output, so a property that holds
 * across all of them is argparse's rule and not this file's opinion.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { cliCommand, formatHelp } from '../js/cli.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SNAP = path.join(ROOT, 'tests', '__snapshots__');
const HELP = path.join(SNAP, 'help');
const TABLE = path.join(ROOT, 'js', 'cli-table.json');
const read = (f) => readFileSync(f, 'utf-8');

const meta = JSON.parse(read(path.join(HELP, '_recorded_with.json')));

/** The verbs argparse rendered — the only ones a recorded text can ever exist for. */
const RECORDED = [...meta.verbs].sort();

/**
 * The verbs the table declares that the recorder never saw, named rather than derived-and-
 * trusted: this list is what turns "a new verb" into a failure instead of an exemption.
 *
 * Each one is a face on a capability that reached the product through the web console and had
 * no subcommand: the catalog endpoint, the MCP read endpoint, the memory-delete endpoint.
 */
const NATIVE = ['catalog', 'mcp', 'memory'];

/** Every command name the shipped table declares. */
const tableNames = () => JSON.parse(read(TABLE)).commands.map((c) => c.name).sort();

/**
 * The layout properties every one of argparse's own 26 texts has.
 *
 * MEASURED, NOT ASSUMED. `the recorded corpus obeys its own layout claims` runs this over all
 * 26 recorded fixtures, so each line below is a statement about what argparse DID and not
 * about what a reader thinks a help text should look like. That is what makes applying the
 * same function to the three native verbs a real gate: they are being held to the reference's
 * layout, by a rule the reference is checked against in the same run.
 *
 * Returns a list of failures so one call can report every violation rather than the first.
 */
function layoutClaims(text, width, verb) {
  const bad = [];
  const say = (ok, why) => { if (!ok) bad.push(`${verb}: ${why}`); };
  say(text.length > 0, 'renders nothing at all');
  say(text.startsWith('usage: '), 'does not open with a usage line');
  say(text.endsWith('\n') && !text.endsWith('\n\n'), 'does not end in exactly one newline');
  say(text.includes('\noptions:\n'), 'has no options section');
  say(/\n {2}-h, --help/.test(text), 'does not list -h/--help first in its options');
  say(!/\n\n\n/.test(text), 'carries a run of blank lines argparse would have collapsed');
  say(!/[ \t]\n/.test(text), 'leaves trailing whitespace on a line');
  for (const line of text.split('\n')) {
    say(line.length <= width, `wraps past the ${width}-column width at ${line.length}`);
  }
  return bad;
}

test('the recording is the shape it claims to be', () => {
  // The positive controls first. Every assertion below is vacuous against an empty corpus, and
  // "the fixtures did not load" and "the port agrees with all of them" are the same green.
  assert.equal(meta.verbs.length, 26,
    '25 subparsers plus argparse\'s `update` alias — the count `test_cli_reference.py` pinned. '
    + 'This is the size of the RECORDED population and it can never grow again: the recorder '
    + 'needs the parser, and the parser is being deleted');
  const files = readdirSync(HELP).filter((f) => f.endsWith('.txt')).sort();
  assert.deepEqual(files, RECORDED.map((v) => `${v}.txt`),
    'the recorded texts and the recorded verb list disagree');
  // The wrap column is an INPUT to every line in every fixture, so a recording that did not
  // write it down could only be believed, never replayed. See `tests/record_help.py`.
  assert.equal(meta.width, meta.columns - 2, 'argparse subtracts two columns from the terminal');
  assert.equal(meta.columns, 80);
  assert.match(meta.recorded_with.python, /^\d+\.\d+$/,
    'a patch digit makes a corpus disagree with itself across two machines that both '
    + 'recorded it correctly');
  for (const v of meta.verbs) assert.ok(read(path.join(HELP, `${v}.txt`)).length > 0);
});

test('every recorded help text is what the port renders', () => {
  for (const v of meta.verbs) {
    const cmd = cliCommand(v);
    assert.notEqual(cmd, null, `js/cli-table.json describes no subcommand '${v}'`);
    assert.equal(formatHelp(cmd, meta.progs[v], meta.width), read(path.join(HELP, `${v}.txt`)),
      `\`${v} --help\` disagrees with the text \`rituals/harness.py\`'s argparse recorded`);
  }
});

test('every verb belongs to exactly one population, and neither is a leftover', () => {
  // ⚠ THE GATE THAT MAKES THE SPLIT A SPLIT. Without it "this verb has no recorded text" is
  // indistinguishable from "this verb is ungated", and the second one arrives silently — a new
  // subcommand is added, the corpus cannot hold it, and every assertion in this file stays
  // green while nothing at all checks it.
  //
  // The two claims are opposite in direction on purpose. A recorded verb the table has lost is
  // a text replayed against nothing; a table verb in neither list is a command with no gate.
  const names = tableNames();
  const missing = RECORDED.filter((v) => !names.includes(v));
  assert.deepEqual(missing, [],
    `the table no longer declares ${missing.join(', ')}, which the corpus has a recorded help `
    + 'text for — the recorded population may shrink only by deleting its fixture, and the '
    + 'fixture can never be re-made');
  assert.deepEqual(names.filter((v) => !RECORDED.includes(v)), NATIVE,
    'a command in js/cli-table.json is in neither population. If it is new, it is Node-native '
    + 'and there is no oracle for it — name it in NATIVE and give it an absolute unit gate. Do '
    + 'NOT declare it to argparse so the recorder emits a text: that records a value authored '
    + 'in Python and compares it to itself');
  // The positive control for every table assertion in this file, and the one thing that says
  // the document is on a PRODUCT path: `package.json`'s `files[]` ships `js/`, so this file
  // needs no row of its own and nothing imports out of `tests/` to parse a verb.
  const live = JSON.parse(read(TABLE));
  assert.equal(live.commands.length, RECORDED.length + NATIVE.length,
    'the table holds a command that is neither recorded nor named as native');
  // `source_sha256` was a hash of `rituals/harness.py`'s bytes — a claim about a file this
  // migration deletes. It went with the move, and nothing may put it back.
  assert.ok(!('source_sha256' in live),
    'the table carries a digest of a file being deleted');
});

test('the recorded corpus obeys its own layout claims', () => {
  // THE POSITIVE CONTROL FOR THE TEST BELOW, and it is the whole reason that one is evidence.
  // `layoutClaims` is applied to the three verbs nothing can compare; here it is applied to 26
  // texts CPython's argparse actually wrote. A claim that failed here would be this file's
  // opinion about layout rather than argparse's rule, and would be worthless imposed on the
  // native three.
  const bad = RECORDED.flatMap((v) => layoutClaims(read(path.join(HELP, `${v}.txt`)),
    meta.width, v));
  assert.deepEqual(bad, [], `a recorded text violates a claim this file makes about layout, so `
    + `the claim is wrong:\n  ${bad.join('\n  ')}`);
});

test('the Node-native verbs render help, and it obeys the same layout rules', () => {
  // WHAT THIS CAN AND CANNOT SAY. It cannot say "argparse would have printed this", because
  // argparse was never asked — there was no subparser. What it says instead is absolute: each
  // one is described by the table, renders a non-empty help text, that text is about the verb
  // the caller asked for, and it obeys every layout property the 26 recorded texts obey.
  for (const verb of NATIVE) {
    const cmd = cliCommand(verb);
    assert.notEqual(cmd, null, `js/cli-table.json describes no subcommand '${verb}'`);
    assert.ok((cmd.help ?? '').length > 20,
      `${verb} carries no summary — it is the only line the docs page and the verb list show`);
    const text = formatHelp(cmd, `geneseed ${verb}`, meta.width);
    assert.deepEqual(layoutClaims(text, meta.width, verb), []);
    assert.ok(text.startsWith(`usage: geneseed ${verb} [-h]`),
      `${verb}'s usage line does not name the verb and its help action first`);
    // …and that the rendering is a function of THIS row rather than of a shared preamble: the
    // command's own summary reaches nothing here, so every argument it declares must.
    for (const a of [...cmd.positionals, ...cmd.options].filter((x) => !x.hidden)) {
      // A positional is spelled by argparse's `_metavar_formatter`: an explicit metavar, else
      // the choices in braces, else the dest — so `action` appears as `{list,rm}` and looking
      // for the dest would ask for a string the reference would never have printed.
      const token = a.names.length ? a.names[0]
        : (a.metavar ?? (a.choices ? `{${a.choices.join(',')}}` : a.dest));
      assert.ok(text.includes(token),
        `${verb} declares ${token} and its help text never mentions it`);
    }
  }
});

test('the table carries the surface argparse hides', () => {
  // EXACTLY WHAT A CARELESS TRANSCRIPTION DROPS, and the direction a comparison of two equally
  // wrong readers can never state. Each of the four `help=argparse.SUPPRESS` arguments binds a
  // real value, and `bin/geneseed-cli.mjs` mis-parses `upgrade v1 imperial`, `sync-self v1`,
  // `bootstrap main imperial` and `web --daemon-internal` without them — the last of which
  // `tests/web_golden.py` passes 95 times a run.
  const live = JSON.parse(read(TABLE));
  const by = Object.fromEntries(live.commands.map((c) => [c.name, c]));
  const hidden = live.commands.flatMap(
    (c) => [...c.positionals, ...c.options].filter((a) => a.hidden).map((a) => [c.name, a.dest]));
  //
  // FIVE, NOT FOUR, and the fifth is why this is an EQUALITY and not four `assertIn`s.
  // `tests/test_cli_reference.py` asserted the four by containment from P10c and could not see
  // that `update` carries `upgrade`'s hidden `ref` as well — the alias is a second command ROW
  // in the table, with its own copy of both positionals, and an edit that dropped it would
  // mis-parse `geneseed update v1 imperial` while `upgrade` stayed correct. A containment
  // check cannot see the fifth, so this stays an equality.
  assert.deepEqual(hidden.map((h) => h.join(' ')).sort(),
    ['bootstrap extra', 'sync-self ref', 'update ref', 'upgrade ref', 'web daemon_internal'],
    'a hidden argument was dropped from the table, or an unexpected one appeared');
  const port = by.web.options.find((a) => a.dest === 'port');
  assert.equal(port.type, 'int',
    '`--port` must be typed, or `--port abc` silently binds the default 4747');
  assert.deepEqual(by.theme.mutex, [['--solid-only', '--transparent-only']],
    'the mutually exclusive group must survive, or the entry accepts a pair argparse refuses');

  // The other half, and it is the half a JSON assertion cannot give: hidden means ABSENT from
  // the rendered text. `update`'s hidden `ref` sits BEFORE its visible `theme`, so a renderer
  // that merely stopped printing hidden rows would still shift `[theme]` in the usage line.
  assert.doesNotMatch(read(path.join(HELP, 'web.txt')), /daemon-internal/);
  assert.doesNotMatch(read(path.join(HELP, 'bootstrap.txt')), /extra/);
  assert.match(read(path.join(HELP, 'update.txt')), /^usage: harness upgrade \[-h\] \[theme\]\n/);
  // …and the control that says the absence above is about `hidden` and not about the renderer
  // dropping positionals: `bootstrap`'s VISIBLE `ref` is there, in the same command as the
  // hidden `extra`.
  assert.match(read(path.join(HELP, 'bootstrap.txt')),
    /^usage: harness bootstrap \[-h\] \[--no-setup\] \[ref\]\n/);
});

test('the port does no %-substitution, and nothing in the table needs it', () => {
  // argparse's `_expand_help` runs `help % vars(action)`, so a literal `%` in a help string
  // changes the rendered text. `formatHelp` does not reproduce that. The claim that the branch
  // is dead is re-derived from the table here rather than trusted, which is what turns a
  // simplification into a gate: the day a help string carries a `%`, this names it.
  const live = JSON.parse(read(TABLE));
  for (const c of live.commands) {
    for (const a of [...c.positionals, ...c.options]) {
      assert.ok(!(a.help ?? '').includes('%'),
        `${c.name} ${a.dest} carries a '%' — argparse expands it and formatHelp does not`);
    }
  }
});

test('every mutually exclusive group is contiguous, which is what the renderer assumes', () => {
  // `_format_actions_usage` splits a group whose members are interleaved with other options
  // into more than one bracketed run; `formatHelp` emits it once, at the first member. One
  // group exists and it is contiguous, so the split is unreachable — measured, not assumed.
  const live = JSON.parse(read(TABLE));
  let groups = 0;
  for (const c of live.commands) {
    const names = c.options.filter((a) => !a.hidden).map((a) => a.names[0]);
    for (const g of c.mutex ?? []) {
      groups += 1;
      const at = g.map((f) => names.indexOf(f));
      assert.ok(at.every((i) => i >= 0), `${c.name}: a group names an option the walk hid`);
      assert.deepEqual(at, at.map((_x, i) => at[0] + i),
        `${c.name}: ${g} is not contiguous, so argparse renders it in more than one run`);
    }
  }
  assert.equal(groups, 1, 'no group was checked, so this test measured nothing');
});

test('prog is a real argument, and the port spells it geneseed', () => {
  // Without this the whole corpus above is satisfied by a renderer that ignores `prog` and
  // hardcodes `harness` — which is the one thing the port must NOT do, since `harness` names
  // the Python file this migration deletes and no user can type it.
  const theme = formatHelp(cliCommand('theme'), 'geneseed theme', meta.width);
  assert.match(theme, /^usage: geneseed theme /);
  assert.doesNotMatch(theme.split('\n')[0], /harness/);
  // The continuation indent moves WITH the prog — it is `len('usage: ') + len(prog) + 1`, which
  // is why the divergence could not have been patched into a recorded text after the fact.
  const recorded = read(path.join(HELP, 'theme.txt')).split('\n');
  const shipped = theme.split('\n');
  assert.equal(recorded[1].length - recorded[1].trimStart().length, 21);
  assert.equal(shipped[1].length - shipped[1].trimStart().length, 22);
  // The alias, where the port deliberately parts company with the reference: argparse hands
  // `update` the parser object it built for `upgrade`, so the reference prints `usage: harness
  // upgrade` for a command the user spelled `update`.
  assert.match(formatHelp(cliCommand('update'), 'geneseed update', meta.width),
    /^usage: geneseed update /);
});

test('both entry points actually print it', () => {
  // THE WIRING. Every assertion above calls `formatHelp` directly, and a renderer nothing
  // reaches is exactly as green as one that is wired — the failure this branch shipped once
  // already, when a narrowing flag's gate was correct and simply not connected.
  //
  // ONE VERB FROM EACH POPULATION AT MINIMUM. `catalog` is here because the wiring is exactly
  // what a Node-native verb has no corpus to prove: the recorded four above reach `printHelp`
  // through a dispatch that predates them, and a new row that was declared in the table but
  // never added to the entry would print help and refuse to run — or the reverse.
  const cases = [['bin/geneseed-cli.mjs', 'geneseed',
    ['theme', 'web', 'update', 'exclude', 'catalog', 'memory']],
  ['bin/geneseed-hook.mjs', 'geneseed-hook', ['context', 'git-gate', 'rule-gate', 'learn']]];
  for (const [entry, prog, verbs] of cases) {
    for (const verb of verbs) {
      const raw = execFileSync(process.execPath, [path.join(ROOT, entry), verb, '--help'],
        { cwd: ROOT, encoding: 'utf-8', env: { ...process.env, COLUMNS: String(meta.columns) } });
      // The ABSOLUTE half, before any normalisation: argparse writes help through a Python text
      // stream, so the line ending is the platform's, and `die` in both entries already matches
      // that. A comparison that normalised first could not tell a port that forgot.
      if (process.platform === 'win32') assert.ok(raw.includes('\r\n'), `${entry} ${verb}: LF`);
      else assert.ok(!raw.includes('\r'), `${entry} ${verb}: CR on a POSIX host`);
      assert.equal(raw.replaceAll('\r\n', '\n'),
        formatHelp(cliCommand(verb), `${prog} ${verb}`, meta.width),
        `${entry} ${verb} --help does not print what formatHelp renders`);
    }
  }
});

test('a --help anywhere in the line wins, and exits 0 — a DECLINED divergence', () => {
  // WHY THE CHECK SITS BEFORE `parse`: `-h` is held at the parser, never in the argument table
  // the walk produced, so `parse` would call it an unrecognized argument. Exit 0 is the half a
  // stdout comparison cannot see — the port answered 2 for all 26.
  //
  // WHAT THIS TEST PINS IS NOT ARGPARSE'S RULE, and it used to say it was. argparse consumes
  // optionals LEFT TO RIGHT, so anything that fails before the `-h` token fires first: two of
  // the four cases below are cases where the REFERENCE exits 2 instead of printing help —
  // `web --port abc -h` is `invalid int value: 'abc'` and `theme --solid-only
  // --transparent-only --help` is `not allowed with argument --solid-only`. The generalisation
  // came from `diff --nope --help`, which prints help on both sides only because an UNKNOWN
  // option is deferred to the end of `parse_known_args`. So these two rows are a divergence the
  // port keeps on purpose — see `docs/declined.md`, "`--help` anywhere on the line wins" — and
  // the other two are parity.
  for (const argv of [['status', '--help'], ['status', '-h'], ['web', '--port', 'abc', '-h'],
    ['theme', '--solid-only', '--transparent-only', '--help']]) {
    const out = execFileSync(process.execPath, [path.join(ROOT, 'bin/geneseed-cli.mjs'), ...argv],
      { cwd: ROOT, encoding: 'utf-8', env: { ...process.env, COLUMNS: String(meta.columns) } });
    assert.match(out, /^usage: geneseed /, `${argv.join(' ')} did not print help`);
  }
});
