/**
 * The recorded CLI surface, replayed against the port — from `node --test`, so it runs on both
 * CI platforms and survives `rituals/harness.py`.
 *
 * WHAT IS RECORDED AND WHY IT HAD TO BE. `cli.json` is generated by walking argparse, and
 * `bin/geneseed-cli.mjs` parses its own argv out of the result — so the CLI's single source of
 * truth is a Python function in a file this migration deletes. `tests/record_help.py` freezes
 * the parser's answers while the parser exists; this replays them.
 *
 * `tests/harness_golden.py` HAS ZERO `--help` CELLS. This surface had never been compared once,
 * and the first comparison found the port answering `geneseed: error: unrecognized arguments:
 * --help` with exit 2 on all 26 verbs. `docs/declined.md` carries the adjudication; what is
 * asserted here is the outcome of it.
 *
 * THE ONE DELIBERATE DIVERGENCE IS AN ARGUMENT, NOT A FUDGE. The reference names itself
 * `harness`, after the file being deleted; the port names itself `geneseed`, as every error it
 * already prints does. `prog` is therefore a parameter of `formatHelp`, the fixtures are
 * replayed with the reference's own prog — so the layout is gated byte for byte — and the
 * shipped spelling is asserted separately, below.
 */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { cliCommand, formatHelp } from '../js/cli.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SNAP = path.join(ROOT, 'tests', '__snapshots__');
const HELP = path.join(SNAP, 'help');
const read = (f) => readFileSync(f, 'utf-8');

const meta = JSON.parse(read(path.join(HELP, '_recorded_with.json')));

test('the recording is the shape it claims to be', () => {
  // The positive controls first. Every assertion below is vacuous against an empty corpus, and
  // "the fixtures did not load" and "the port agrees with all of them" are the same green.
  assert.equal(meta.verbs.length, 26,
    '25 subparsers plus argparse\'s `update` alias — the count `test_cli_reference.py` pins');
  const files = readdirSync(HELP).filter((f) => f.endsWith('.txt')).sort();
  assert.deepEqual(files, [...meta.verbs].sort().map((v) => `${v}.txt`),
    'the recorded texts and the recorded verb list disagree');
  // The wrap column is an INPUT to every line in every fixture, so a recording that did not
  // write it down could only be believed, never replayed. See `tests/record_help.py`.
  assert.equal(meta.width, meta.columns - 2, 'argparse subtracts two columns from the terminal');
  assert.equal(meta.columns, 80);
  assert.match(meta.recorded_with.python, /^\d+\.\d+$/,
    'a patch digit makes a corpus disagree with itself across two machines that both '
    + 'recorded it correctly');
  for (const v of meta.verbs) assert.ok(read(path.join(HELP, `${v}.txt`)).length > 0);
});

test('every recorded help text is what the port renders', () => {
  for (const v of meta.verbs) {
    const cmd = cliCommand(v);
    assert.notEqual(cmd, null, `cli.json describes no subcommand '${v}'`);
    assert.equal(formatHelp(cmd, meta.progs[v], meta.width), read(path.join(HELP, `${v}.txt`)),
      `\`${v} --help\` disagrees with the text \`rituals/harness.py\`'s argparse recorded`);
  }
});

test('the recorded reference is cli.json minus the digest of a file being deleted', () => {
  // `source_sha256` is a hash of `rituals/harness.py`'s bytes. Freezing it would freeze a claim
  // about a file that will not exist — and the live digest is gated, for as long as both exist,
  // by `tests/test_cli_reference.py`. Everything else must survive verbatim, because it is what
  // the JS table has to reproduce when `cli.json` goes.
  const live = JSON.parse(read(path.join(ROOT, 'cli.json')));
  const recorded = JSON.parse(read(path.join(SNAP, 'cli_reference.json')));
  assert.ok('source_sha256' in live, 'cli.json no longer carries the digest this test excludes');
  assert.ok(!('source_sha256' in recorded), 'the recording froze a digest of a deleted file');
  delete live.source_sha256;
  assert.deepEqual(recorded, live);
});

test('the recording carries the surface argparse hides', () => {
  // EXACTLY WHAT A CARELESS TRANSCRIPTION DROPS, and the direction a comparison of two equally
  // wrong readers can never state. Each of the four `help=argparse.SUPPRESS` arguments binds a
  // real value, and `bin/geneseed-cli.mjs` mis-parses `upgrade v1 imperial`, `sync-self v1`,
  // `bootstrap main imperial` and `web --daemon-internal` without them — the last of which
  // `tests/web_golden.py` passes 95 times a run.
  const recorded = JSON.parse(read(path.join(SNAP, 'cli_reference.json')));
  const by = Object.fromEntries(recorded.commands.map((c) => [c.name, c]));
  const hidden = recorded.commands.flatMap(
    (c) => [...c.positionals, ...c.options].filter((a) => a.hidden).map((a) => [c.name, a.dest]));
  //
  // FIVE, NOT FOUR, and the fifth is why this is an EQUALITY and not four `assertIn`s.
  // `tests/test_cli_reference.py` has asserted the four by containment since P10c and could
  // not see that `update` carries `upgrade`'s hidden `ref` as well — the alias is a second
  // command ROW in `cli.json`, with its own copy of both positionals, and a transcription that
  // dropped it would mis-parse `geneseed update v1 imperial` while `upgrade` stayed correct.
  // Found by writing the equality this task's brief specified with four rows in it.
  assert.deepEqual(hidden.map((h) => h.join(' ')).sort(),
    ['bootstrap extra', 'sync-self ref', 'update ref', 'upgrade ref', 'web daemon_internal'],
    'a hidden argument was dropped from the recording, or an unexpected one appeared');
  const port = by.web.options.find((a) => a.dest === 'port');
  assert.equal(port.type, 'int',
    '`--port` must be typed, or `--port abc` silently binds the default 4747');
  assert.deepEqual(by.theme.mutex, [['--solid-only', '--transparent-only']],
    'the mutually exclusive group must survive, or the entry accepts a pair argparse refuses');

  // The other half, and it is the half a JSON assertion cannot give: hidden means ABSENT from
  // the rendered text. `update`'s hidden `ref` sits BEFORE its visible `theme`, so a renderer
  // that merely stopped printing hidden rows would still shift `[theme]` in the usage line.
  assert.doesNotMatch(read(path.join(HELP, 'web.txt')), /daemon-internal/);
  assert.doesNotMatch(read(path.join(HELP, 'bootstrap.txt')), /extra/);
  assert.match(read(path.join(HELP, 'update.txt')), /^usage: harness upgrade \[-h\] \[theme\]\n/);
  // …and the control that says the absence above is about `hidden` and not about the renderer
  // dropping positionals: `bootstrap`'s VISIBLE `ref` is there, in the same command as the
  // hidden `extra`.
  assert.match(read(path.join(HELP, 'bootstrap.txt')),
    /^usage: harness bootstrap \[-h\] \[--no-setup\] \[ref\]\n/);
});

test('the port does no %-substitution, and nothing in cli.json needs it', () => {
  // argparse's `_expand_help` runs `help % vars(action)`, so a literal `%` in a help string
  // changes the rendered text. `formatHelp` does not reproduce that. The claim that the branch
  // is dead is re-derived from `cli.json` here rather than trusted, which is what turns a
  // simplification into a gate: the day a help string carries a `%`, this names it.
  const live = JSON.parse(read(path.join(ROOT, 'cli.json')));
  for (const c of live.commands) {
    for (const a of [...c.positionals, ...c.options]) {
      assert.ok(!(a.help ?? '').includes('%'),
        `${c.name} ${a.dest} carries a '%' — argparse expands it and formatHelp does not`);
    }
  }
});

test('every mutually exclusive group is contiguous, which is what the renderer assumes', () => {
  // `_format_actions_usage` splits a group whose members are interleaved with other options
  // into more than one bracketed run; `formatHelp` emits it once, at the first member. One
  // group exists and it is contiguous, so the split is unreachable — measured, not assumed.
  const live = JSON.parse(read(path.join(ROOT, 'cli.json')));
  let groups = 0;
  for (const c of live.commands) {
    const names = c.options.filter((a) => !a.hidden).map((a) => a.names[0]);
    for (const g of c.mutex ?? []) {
      groups += 1;
      const at = g.map((f) => names.indexOf(f));
      assert.ok(at.every((i) => i >= 0), `${c.name}: a group names an option the walk hid`);
      assert.deepEqual(at, at.map((_x, i) => at[0] + i),
        `${c.name}: ${g} is not contiguous, so argparse renders it in more than one run`);
    }
  }
  assert.equal(groups, 1, 'no group was checked, so this test measured nothing');
});

test('prog is a real argument, and the port spells it geneseed', () => {
  // Without this the whole corpus above is satisfied by a renderer that ignores `prog` and
  // hardcodes `harness` — which is the one thing the port must NOT do, since `harness` names
  // the Python file this migration deletes and no user can type it.
  const theme = formatHelp(cliCommand('theme'), 'geneseed theme', meta.width);
  assert.match(theme, /^usage: geneseed theme /);
  assert.doesNotMatch(theme.split('\n')[0], /harness/);
  // The continuation indent moves WITH the prog — it is `len('usage: ') + len(prog) + 1`, which
  // is why the divergence could not have been patched into a recorded text after the fact.
  const recorded = read(path.join(HELP, 'theme.txt')).split('\n');
  const shipped = theme.split('\n');
  assert.equal(recorded[1].length - recorded[1].trimStart().length, 21);
  assert.equal(shipped[1].length - shipped[1].trimStart().length, 22);
  // The alias, where the port deliberately parts company with the reference: argparse hands
  // `update` the parser object it built for `upgrade`, so the reference prints `usage: harness
  // upgrade` for a command the user spelled `update`.
  assert.match(formatHelp(cliCommand('update'), 'geneseed update', meta.width),
    /^usage: geneseed update /);
});

test('both entry points actually print it', () => {
  // THE WIRING. Every assertion above calls `formatHelp` directly, and a renderer nothing
  // reaches is exactly as green as one that is wired — the failure this branch shipped once
  // already, when a narrowing flag's gate was correct and simply not connected.
  const cases = [['bin/geneseed-cli.mjs', 'geneseed', ['theme', 'web', 'update', 'exclude']],
    ['bin/geneseed-hook.mjs', 'geneseed-hook', ['context', 'git-gate', 'rule-gate', 'learn']]];
  for (const [entry, prog, verbs] of cases) {
    for (const verb of verbs) {
      const raw = execFileSync(process.execPath, [path.join(ROOT, entry), verb, '--help'],
        { cwd: ROOT, encoding: 'utf-8', env: { ...process.env, COLUMNS: String(meta.columns) } });
      // The ABSOLUTE half, before any normalisation: argparse writes help through a Python text
      // stream, so the line ending is the platform's, and `die` in both entries already matches
      // that. A comparison that normalised first could not tell a port that forgot.
      if (process.platform === 'win32') assert.ok(raw.includes('\r\n'), `${entry} ${verb}: LF`);
      else assert.ok(!raw.includes('\r'), `${entry} ${verb}: CR on a POSIX host`);
      assert.equal(raw.replaceAll('\r\n', '\n'),
        formatHelp(cliCommand(verb), `${prog} ${verb}`, meta.width),
        `${entry} ${verb} --help does not print what formatHelp renders`);
    }
  }
});

test('a --help anywhere in the line wins, and exits 0', () => {
  // argparse's rule, and the reason the check sits before `parse`: `-h` is held at the parser,
  // never in the argument table `cli.json` walks, so `parse` calls it an unrecognized argument.
  // Exit 0 is the half a stdout comparison cannot see — the port answered 2 for all 26.
  for (const argv of [['status', '--help'], ['status', '-h'], ['web', '--port', 'abc', '-h'],
    ['theme', '--solid-only', '--transparent-only', '--help']]) {
    const out = execFileSync(process.execPath, [path.join(ROOT, 'bin/geneseed-cli.mjs'), ...argv],
      { cwd: ROOT, encoding: 'utf-8', env: { ...process.env, COLUMNS: String(meta.columns) } });
    assert.match(out, /^usage: geneseed /, `${argv.join(' ')} did not print help`);
  }
});
