#!/usr/bin/env python3
"""Record `cli.json` and the 26 `--help` texts, from the parser that still exists.

WHAT THIS IS FOR. `cli.json` is GENERATED by walking `rituals/harness.py`'s argparse tree, and
`bin/geneseed-cli.mjs` parses its own argv out of the result — so the CLI's single source of
truth is a Python function in a file this migration deletes. A later phase moves that table
into JS and drops `cli.json`. This writes down what the transcription has to reproduce while
the parser that produces it is still here to be asked.

TWO ARTEFACTS, for two different questions:

  * `cli_reference.json` — the tracked `cli.json` MINUS `source_sha256`. The digest is over
    `rituals/harness.py`'s bytes; freezing it would freeze a claim about a file that will not
    exist, and `tests/test_cli_reference.py` already gates the live digest against the live
    parser for as long as both are here.
  * `help/<verb>.txt` — `parser.format_help()` for each of the 26 invocable names, verbatim.
    This surface had NEVER been compared between the two implementations: `tests/
    harness_golden.py` has zero `--help` cells, and the port answered every one of them with
    `geneseed: error: unrecognized arguments: --help` and exit 2. See `docs/declined.md` for
    the adjudication.

IN-PROCESS, NOT 26 SUBPROCESSES, and it is not only the four seconds. `print_help()` writes
through a Python text stream, so a captured stdout is CRLF on Windows and LF on POSIX — the
recording would split into platform halves for a text that has no platform in it. `format_help()`
returns the string before any newline translation, so one corpus serves both runners and
`tests/cli_help.test.mjs` can replay it from `node --test` on either.

COLUMNS IS FENCED, AND IT IS THE TENTH ROT VECTOR THIS BRANCH HAS FOUND. argparse's
`HelpFormatter` takes its width from `shutil.get_terminal_size().columns - 2`, which reads
`$COLUMNS` and then the tty. Recorded unfenced, every wrapped line in this corpus would be a
property of the recorder's terminal. `COLUMNS` is pinned to 80 here, the pin is WRITTEN DOWN in
`_recorded_with.json`, and the replay passes the same number in rather than reading anything.

THE MACHINE-STATE GUARD IS BORROWED, NOT REWRITTEN. `tests/test_pure_function_parity.py`'s
`_refuse_machine_state` is the detector Task 8 earned and Tasks 9b/9c extended; a tenth bespoke
recorder would be a tenth chance to miss what it already knows. It runs over every recorded
text before a byte is written.
"""
from __future__ import annotations

import json
import os
import sys
from contextlib import contextmanager
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "rituals"))
sys.path.insert(0, str(ROOT / "tests"))

import harness  # noqa: E402
import test_pure_function_parity as guard  # noqa: E402

#: argparse's width is `shutil.get_terminal_size().columns - 2`, and `get_terminal_size` reads
#: this variable first.
#:
#: SET AND RESTORED AROUND THE FORMATTER, never at import. `tests/test_cli_reference.py` imports
#: this module inside `python -m unittest discover`, and a module that pinned `$COLUMNS` on the
#: way in would be setting it for every sibling test in the same process — P5a's
#: fixture-SETS-a-variable hole, where `PYTHONUTF8=1` made a bare `text=True` accidentally right
#: in one suite and wrong everywhere else.
COLUMNS = 80


@contextmanager
def _fenced_columns():
    was = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = str(COLUMNS)
    try:
        yield
    finally:
        if was is None:
            os.environ.pop("COLUMNS", None)
        else:
            os.environ["COLUMNS"] = was


def _subparsers(parser) -> "dict[str, object]":
    """Every invocable name argparse dispatches, INCLUDING the aliases.

    `_SubParsersAction.choices` is the name→parser map and an alias is a second key pointing at
    the same parser object — which is why `update --help` prints `usage: harness upgrade`, and
    why the prog has to be read off the parser rather than composed from the name.
    """
    for action in parser._actions:  # noqa: SLF001 — the walk `gen_cli_reference.py` also does
        if hasattr(action, "choices") and isinstance(action.choices, dict):
            return dict(action.choices)
    raise SystemExit("no subparsers on the harness parser — the walk found nothing to record")


def help_texts(subs: dict, names: "list[str]") -> "dict[str, str]":
    """`format_help()` for each name, at the pinned width — the ONE place that pin is applied.

    `tests/test_cli_reference.py` re-derives the same texts to check the recording has not gone
    stale, and a second `format_help()` call outside the fence would render at whatever width
    the test runner's terminal happens to be, then blame the corpus for the difference.
    """
    with _fenced_columns():
        return {name: subs[name].format_help() for name in names}


def record(dest: Path) -> "tuple[Path, list[Path]]":
    parser = harness.build_argparser()
    subs = _subparsers(parser)

    reference = {k: v for k, v in
                 json.loads(harness.CLI_JSON.read_text(encoding="utf-8")).items()
                 if k != "source_sha256"}
    named = [c["name"] for c in reference["commands"]]
    missing = sorted(set(named) ^ set(subs))
    if missing:
        raise SystemExit(f"cli.json and the parser disagree on which names exist: {missing}")

    helps = help_texts(subs, named)
    progs = {name: subs[name].prog for name in named}

    # The guard's own shape: a document of strings, walked and probed before anything is
    # written. `help` and `prog` are ANSWERS — the formatter produced them — so a machine path
    # in either is an unconditional refusal, with no corpus-text exemption to hide behind.
    guard._refuse_machine_state({"help": helps, "prog": progs, "reference": reference})

    dest.mkdir(parents=True, exist_ok=True)
    ref_path = dest / "cli_reference.json"
    ref_path.write_text(json.dumps(reference, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8", newline="\n")

    help_dir = dest / "help"
    help_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in named:
        f = help_dir / f"{name}.txt"
        f.write_text(helps[name], encoding="utf-8", newline="\n")
        written.append(f)
    meta = help_dir / "_recorded_with.json"
    meta.write_text(json.dumps({
        # The wrap column, WRITTEN DOWN because it is an input to every line above. A corpus
        # that does not say what width it was rendered at cannot be replayed, only believed.
        "columns": COLUMNS,
        "width": COLUMNS - 2,
        # `parser.prog` per name, read off argparse rather than composed: the alias shares the
        # canonical parser and therefore its prog, and the replay needs the same string to
        # reproduce the usage line's continuation indent.
        "progs": progs,
        "verbs": named,
        "recorded_with": guard._recorded_with(),
    }, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    written.append(meta)
    return ref_path, written


if __name__ == "__main__":
    where = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "tests" / "__snapshots__")
    ref, files = record(where)
    print(f"recorded {ref}")
    print(f"recorded {len(files)} files under {files[0].parent}")
