#!/usr/bin/env python3
"""Record `cli.json` and the 26 `--help` texts, from the parser that still exists.

WHAT THIS IS FOR. `cli.json` is GENERATED by walking `rituals/harness.py`'s argparse tree, and
`bin/geneseed-cli.mjs` parses its own argv out of the result — so the CLI's single source of
truth is a Python function in a file this migration deletes. A later phase moves that table
into JS and drops `cli.json`. This writes down what the transcription has to reproduce while
the parser that produces it is still here to be asked.

TWO ARTEFACTS, for two different questions:

  * `cli_reference.json` — the tracked `cli.json` MINUS `source_sha256`. The digest is over
    `rituals/harness.py`'s bytes; freezing it would freeze a claim about a file that will not
    exist, and `tests/test_cli_reference.py` already gates the live digest against the live
    parser for as long as both are here.
  * `help/<verb>.txt` — `parser.format_help()` for each of the 26 invocable names, verbatim.
    This surface had NEVER been compared between the two implementations: `tests/
    harness_golden.py` has zero `--help` cells, and the port answered every one of them with
    `geneseed: error: unrecognized arguments: --help` and exit 2. See `docs/declined.md` for
    the adjudication.

IN-PROCESS, NOT 26 SUBPROCESSES, and it is not only the four seconds. `print_help()` writes
through a Python text stream, so a captured stdout is CRLF on Windows and LF on POSIX — the
recording would split into platform halves for a text that has no platform in it. `format_help()`
returns the string before any newline translation, so one corpus serves both runners and
`tests/cli_help.test.mjs` can replay it from `node --test` on either.

COLUMNS IS FENCED, AND IT IS THE TENTH ROT VECTOR THIS BRANCH HAS FOUND. argparse's
`HelpFormatter` takes its width from `shutil.get_terminal_size().columns - 2`, which reads
`$COLUMNS` and then the tty. Recorded unfenced, every wrapped line in this corpus would be a
property of the recorder's terminal. `COLUMNS` is pinned to 80 here, the pin is WRITTEN DOWN in
`_recorded_with.json`, and the replay passes the same number in rather than reading anything.

THE MACHINE-STATE GUARD IS BORROWED, NOT REWRITTEN. `tests/test_pure_function_parity.py`'s
`_refuse_machine_state` is the detector Task 8 earned and Tasks 9b/9c extended; a tenth bespoke
recorder would be a tenth chance to miss what it already knows. It runs over every recorded
text before a byte is written.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import textwrap
from contextlib import contextmanager
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "rituals"))
sys.path.insert(0, str(ROOT / "tests"))

import harness  # noqa: E402
import test_pure_function_parity as guard  # noqa: E402

#: argparse's width is `shutil.get_terminal_size().columns - 2`, and `get_terminal_size` reads
#: this variable first.
#:
#: SET AND RESTORED AROUND THE FORMATTER, never at import. `tests/test_cli_reference.py` imports
#: this module inside `python -m unittest discover`, and a module that pinned `$COLUMNS` on the
#: way in would be setting it for every sibling test in the same process — P5a's
#: fixture-SETS-a-variable hole, where `PYTHONUTF8=1` made a bare `text=True` accidentally right
#: in one suite and wrong everywhere else.
COLUMNS = 80


@contextmanager
def _fenced_columns():
    was = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = str(COLUMNS)
    try:
        yield
    finally:
        if was is None:
            os.environ.pop("COLUMNS", None)
        else:
            os.environ["COLUMNS"] = was


def _subparsers(parser) -> "dict[str, object]":
    """Every invocable name argparse dispatches, INCLUDING the aliases.

    `_SubParsersAction.choices` is the name→parser map and an alias is a second key pointing at
    the same parser object — which is why `update --help` prints `usage: harness upgrade`, and
    why the prog has to be read off the parser rather than composed from the name.
    """
    for action in parser._actions:  # noqa: SLF001 — the walk `gen_cli_reference.py` also does
        if hasattr(action, "choices") and isinstance(action.choices, dict):
            return dict(action.choices)
    raise SystemExit("no subparsers on the harness parser — the walk found nothing to record")


def help_texts(subs: dict, names: "list[str]") -> "dict[str, str]":
    """`format_help()` for each name, at the pinned width — the ONE place that pin is applied.

    `tests/test_cli_reference.py` re-derives the same texts to check the recording has not gone
    stale, and a second `format_help()` call outside the fence would render at whatever width
    the test runner's terminal happens to be, then blame the corpus for the difference.
    """
    with _fenced_columns():
        return {name: subs[name].format_help() for name in names}


class Gh139065(textwrap.TextWrapper):
    """`if self.break_long_words and space_left > 0:` — the whole of the upstream fix.

    Returning early is exactly equivalent to failing that condition: the `elif not cur_line`
    arm below it is unreachable when `space_left <= 0`, because an empty `cur_line` has
    `cur_len == 0` and so `space_left == width` (or 1 when width < 1).

    THE RECORDER OWNS THE ORACLE CORRECTION, and `tests/test_cli_reference.py` imports it from
    here rather than keeping a second copy: the live sweeps and the frozen recording must
    normalise the same way or the corpus and the gate that checks it disagree about which
    CPython they mean. gh-139065 (main 1c598e0, 3.13 backport b1bc743) first shipped in
    3.13.14; `ci.yml` pins `python-version: "3.13"` with no patch digit, so the two sides of
    this branch really did measure different reference behaviour once — see Task 10b."""

    def _handle_long_word(self, reversed_chunks, cur_line, cur_len, width):
        if (1 if width < 1 else width - cur_len) <= 0:
            return
        super()._handle_long_word(reversed_chunks, cur_line, cur_len, width)


#: Detected BY BEHAVIOUR — a line of exactly `width` followed by a word too long for any line
#: yields 'ab ' pre-fix — so a distro backport is read correctly and `sys.version_info` is never
#: consulted.
PRE_GH139065 = textwrap.wrap("ab cdefgh", 3)[0] == "ab "

#: The band `_format_action` can hand `textwrap.wrap`: the help column floors at 11 and 198 is
#: what a 200-column terminal gives. The 26 recorded help fixtures only ever exercise 54..64.
WRAP_WIDTHS = range(11, 199)


def wrap_cases() -> "list[str]":
    """Every help string this parser carries, as `_split_lines` hands it to `textwrap.wrap`.

    `_whitespace_matcher` is `re.compile(r'\\s+', re.ASCII)`, so the collapse is the ASCII class
    and a help string carrying U+00A0 keeps it. Read from `cli.json` rather than from argparse
    because that file is what both implementations already read."""
    data = json.loads(harness.CLI_JSON.read_text(encoding="utf-8"))
    texts = ["show this help message and exit"]  # argparse's own, absent from the file
    for c in data["commands"]:
        texts += [a["help"] for a in c["positionals"] + c["options"] if a["help"]]
    return [t for t in (re.sub(r"\s+", " ", raw, flags=re.ASCII).strip() for raw in texts) if t]


def record_textwrap(dest: Path) -> Path:
    """`textwrap.wrap` frozen — THE ONE CPYTHON ORACLE P1 RECORDED NOWHERE ELSE.

    Every other CPython-only oracle on this branch was written down while a CPython was still
    there to ask: `primitives/{win32,posix}.json`, `dwidth.json`, `win_user_path.json`,
    `help/`. `pyTextWrap` — 40 lines of `js/cli.mjs` including a hand-transcribed `WORDSEP` —
    was left as a LIVE comparison against the running interpreter, so its gate dies with
    `rituals/harness.py` and what survives is 26 fixtures at one width. That is precisely the
    coverage the live sweep's own docstring records as having proved nothing: a wholly
    different algorithm (greedy space-only wrap) passed all 26.

    THE SAME SHAPE AS `dwidth.json`: the case list, the width band, a sha256 over the full
    matrix, and a handful of readable sample rows. The canonical form is
    `separators=(",", ":")` with `ensure_ascii=False`, which is byte-for-byte what
    `JSON.stringify` produces, so the Node replay can hash it without a Python.

    RECORDED AGAINST THE NORMALISED ORACLE, never the raw local interpreter: on a pre-3.13.14
    CPython the upstream one-liner is applied first, or this would freeze the behaviour CPython
    already fixed and the port already targets."""
    wrapper = Gh139065 if PRE_GH139065 else textwrap.TextWrapper
    if wrapper(width=3).wrap("ab cdefgh") != ["ab", "cde", "fgh"]:
        raise SystemExit(
            "REFUSING TO RECORD — the oracle is not post-gh-139065, so this recording would "
            "freeze the interpreter's patch digit rather than the reference's answer.")
    cases = wrap_cases()
    if len(cases) < 30:
        raise SystemExit(f"REFUSING TO RECORD — only {len(cases)} help strings; the corpus "
                         "collapsed and would gate nothing.")
    widths = list(WRAP_WIDTHS)
    matrix = [[wrapper(width=w).wrap(t) for w in widths] for t in cases]
    canonical = json.dumps(matrix, separators=(",", ":"), ensure_ascii=False)
    doc = {
        "corpus": "textwrap",
        "recorded_with": guard._recorded_with(),
        # DECLARED, not implied: which side of gh-139065 these answers are on. A future reader
        # comparing this file against a 3.13.5 interpreter needs to know it will disagree.
        "oracle": "textwrap.wrap, post-gh-139065",
        "widths": [widths[0], widths[-1] + 1],
        "cases": cases,
        "rows": len(cases) * len(widths),
        "sha256": hashlib.sha256(canonical.encode("utf-8")).hexdigest(),
        # Readable rows, so a human can see what the hash is over. The widths are the ones
        # Task 10b's divergences actually landed on plus one inside the fixtures' own band.
        "sample": {f"{i}@{w}": matrix[i][widths.index(w)]
                   for i in (0, len(cases) // 2, len(cases) - 1) for w in (11, 15, 60)},
        "matrix": matrix,
    }
    dest.mkdir(parents=True, exist_ok=True)
    out = dest / "textwrap.json"
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
                   encoding="utf-8", newline="\n")
    return out


def record(dest: Path) -> "tuple[Path, list[Path]]":
    parser = harness.build_argparser()
    subs = _subparsers(parser)

    reference = {k: v for k, v in
                 json.loads(harness.CLI_JSON.read_text(encoding="utf-8")).items()
                 if k != "source_sha256"}
    named = [c["name"] for c in reference["commands"]]
    missing = sorted(set(named) ^ set(subs))
    if missing:
        raise SystemExit(f"cli.json and the parser disagree on which names exist: {missing}")

    helps = help_texts(subs, named)
    progs = {name: subs[name].prog for name in named}

    # The guard's own shape: a document of strings, walked and probed before anything is
    # written. `help` and `prog` are ANSWERS — the formatter produced them — so a machine path
    # in either is an unconditional refusal, with no corpus-text exemption to hide behind.
    guard._refuse_machine_state({"help": helps, "prog": progs, "reference": reference})

    dest.mkdir(parents=True, exist_ok=True)
    ref_path = dest / "cli_reference.json"
    ref_path.write_text(json.dumps(reference, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8", newline="\n")

    help_dir = dest / "help"
    help_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in named:
        f = help_dir / f"{name}.txt"
        f.write_text(helps[name], encoding="utf-8", newline="\n")
        written.append(f)
    meta = help_dir / "_recorded_with.json"
    meta.write_text(json.dumps({
        # The wrap column, WRITTEN DOWN because it is an input to every line above. A corpus
        # that does not say what width it was rendered at cannot be replayed, only believed.
        "columns": COLUMNS,
        "width": COLUMNS - 2,
        # `parser.prog` per name, read off argparse rather than composed: the alias shares the
        # canonical parser and therefore its prog, and the replay needs the same string to
        # reproduce the usage line's continuation indent.
        "progs": progs,
        "verbs": named,
        "recorded_with": guard._recorded_with(),
    }, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    written.append(meta)
    written.append(record_textwrap(dest))
    return ref_path, written


if __name__ == "__main__":
    where = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "tests" / "__snapshots__")
    ref, files = record(where)
    print(f"recorded {ref}")
    print(f"recorded {len(files)} files under {files[0].parent}")
